name: Build, Sign, and Release Golang App

on:
  push:
    tags:
      - "v*"  # Trigger on version tag pushes

permissions:
  id-token: write  # Allows GitHub OIDC identity
  contents: write  # Enables uploading assets
  pages: write  # Allows release notes and assets uploading
  actions: write  # Required for creating a release

jobs:
  build-and-sign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.8.1

      - name: Check Cosign install
        run: cosign version

      - name: Build for Linux
        run: |
          echo "Building for Linux"
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o smtpservice

      - name: Build for Windows x64
        run: |
          echo "Building for Windows x64"
          GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o smtpservice_x64.exe

      - name: Build for Windows x86
        run: |
          echo "Building for Windows x86"
          GOOS=windows GOARCH=386 go build -ldflags="-s -w" -o smtpservice_x86.exe

      - name: Sign Linux Binary with Cosign
        run: cosign sign-blob --yes --oidc-provider=github smtpservice --output-signature smtpservice.sig

      - name: Sign Windows x64 Binary with Cosign
        run: cosign sign-blob --yes --oidc-provider=github smtpservice_x64.exe --output-signature smtpservice_x64.exe.sig

      - name: Sign Windows x86 Binary with Cosign
        run: cosign sign-blob --yes --oidc-provider=github smtpservice_x86.exe --output-signature smtpservice_x86.exe.sig

      # Combine Linux binary, signature, and config.ini into a zip
      - name: Create Linux Package
        run: |
          mkdir linux_package
          cp smtpservice smtpservice.sig config.ini linux_package/
          zip -r smtpservice-linux.zip linux_package

      - name: Upload Linux Zip as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: smtpservice-linux-zip
          path: smtpservice-linux.zip

      # Combine Windows x64 binary, signature, and config.ini into a zip
      - name: Create Windows x64 Package
        run: |
          mkdir win_x64_package
          cp smtpservice_x64.exe smtpservice_x64.exe.sig config.ini win_x64_package/
          zip -r smtpservice-windows-x64.zip win_x64_package

      - name: Upload Windows x64 Zip as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: smtpservice-windows-x64-zip
          path: smtpservice-windows-x64.zip

      # Combine Windows x86 binary, signature, and config.ini into a zip
      - name: Create Windows x86 Package
        run: |
          mkdir win_x86_package
          cp smtpservice_x86.exe smtpservice_x86.exe.sig config.ini win_x86_package/
          zip -r smtpservice-windows-x86.zip win_x86_package

      - name: Upload Windows x86 Zip as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: smtpservice-windows-x86-zip
          path: smtpservice-windows-x86.zip

  create-release:
    runs-on: ubuntu-latest
    needs: build-and-sign  # Wait for the build-and-sign job to complete

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Download zipped artifacts directly
      - name: Download Linux Zip
        uses: actions/download-artifact@v4
        with:
          name: smtpservice-linux-zip

      - name: Download Windows x64 Zip
        uses: actions/download-artifact@v4
        with:
          name: smtpservice-windows-x64-zip

      - name: Download Windows x86 Zip
        uses: actions/download-artifact@v4
        with:
          name: smtpservice-windows-x86-zip

      # Create the GitHub release with all zipped files attached
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            smtpservice-linux.zip
            smtpservice-windows-x64.zip
            smtpservice-windows-x86.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Output Release URL
        run: 'echo "Release URL: ${{ steps.create_release.outputs.upload_url }}"'